# Generated by Django 4.2.6 on 2023-10-29 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_message_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
