# Generated by Django 4.2.6 on 2023-10-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='money',
            field=models.BigIntegerField(default=0),
        ),
    ]
