# Generated by Django 4.2.6 on 2023-10-28 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_author_name_remove_author_password_and_more'),
    ]

    operations = [
    ]
