# Generated by Django 4.2.6 on 2023-10-26 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20231025_1701'),
    ]

    operations = [
    ]
