# Generated by Django 4.2.6 on 2023-10-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_member_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='money',
            field=models.BigIntegerField(default=100000),
        ),
    ]
