# Generated by Django 4.2.6 on 2023-10-26 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20231026_2013'),
        ('main', '0003_delete_buku'),
    ]

    operations = [
    ]
