# Generated by Django 4.2.6 on 2023-10-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isAccept',
        ),
        migrations.AddField(
            model_name='book',
            name='statusAccept',
            field=models.CharField(choices=[('ACCEPT', 'Accept'), ('WAITING', 'Waiting'), ('DENIED', 'Denied'), ('NO STATUS', 'No Status')], default='NO STATUS', max_length=10),
        ),
    ]
