# Generated by Django 4.2.6 on 2023-10-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20231027_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='statusAccept',
            field=models.CharField(choices=[('ACCEPT', 'Accept'), ('WAITING', 'Waiting'), ('DENIED', 'Denied')], default='WAITING', max_length=10),
        ),
    ]
