# Generated by Django 4.2.6 on 2023-10-26 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20231026_1553'),
    ]

    operations = [
    ]
