# Generated by Django 4.2.6 on 2023-10-26 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20231026_2014'),
        ('book', '0005_auto_20231026_1625'),
    ]

    operations = [
    ]
